### ISSUE TITLE
Non-linear gray scale value change

### ISSUE THREAD

**Issue by tangmc0210** [elgw/deconwolf#78]
Congratulations! I am so glad to see your publication and it is really a nice work. 
In my project I am trying to use the ratio of different fluorophores to encode information so that I read gray scale of one spot in multiple channels and decode the spot by calculating the ratio of gray scale in each channel. I want to use widefiled to image a 50um or so slide but the deconvolution seems resulting bias in intensity level. For example, a spot with grayscale 200, 1000 in ch1, ch2 changes to 100, 2000 after deconvolution. Can you offer some advice?

**Comment by elgw** [comment]
Hello,

While deconvolution can be expressed as a linear problem, the relationship between input and output pixel values is not linear.

Just to be on the same line: If the pixel values in image $J$ depends linearly on the pixel values in image $I$ that could be expressed as

$$
J(x,y,z) = c_0 + c_1 I(x,y,z)
$$

Clearly that would not be very useful as the input and output would looks the same after adjusting contrast and brightness.

Please note that `dw` <ins>scales the images before writing them to disk</ins> (to make most use of the 16-bit format). The scaling factor can be found in the `.log.txt` files (so that you can correct for that afterwards). If you don't want automatic scaling, use the `--float` option (output images will use 2x the disk space), or set an explicit scaling with the `--scaling` argument.

It sounds reasonable to integrate over a distribution of wavelengths when creating the PSF, unfortunately you will not find such feature in `dw` at the moment. Possibly you could get better results with and experimental PSF, but for that you would also have to find another program/implement yourself.

Cheers,
Erik

**Comment by tangmc0210** [comment]
Thanks a lot! I would try to get better results.
